language: node_js
node_js: "8.8.1"

before_script:
    - chmod +x ./jake.sh
    - chmod +x ./tests/build/scripts/run_jake.sh
    - export DISPLAY=:99.0
    - npm install karma-firefox-launcher
    - node node_modules/gulp/bin/gulp.js build

script: "./jake.sh loose=true capture=Firefox"
